module tb_ripple_carry_adder_4bit;
    reg [3:0] A;
    reg [3:0] B;
    reg Cin;
    wire [3:0] S;
    wire Cout;
    ripple_carry_adder_4bit_tb(
        .A(A),
        .B(B),
        .Cin(Cin),
        .S(S),
        .Cout(Cout)
    );
    initial begin
        A = 4'b0010; B = 4'b0100; Cin = 1'b0; #10;
        A = 4'b0101; B = 4'b0011; Cin = 1'b1; #10;
        A = 4'b0111; B = 4'b0001; Cin = 1'b0; #10;
        A = 4'b1111; B = 4'b0001; Cin = 1'b0; #10;
        A = 4'b1111; B = 4'b1111; Cin = 1'b1; #10;
end    
endmodule